# Generated by Django 5.2 on 2025-05-12 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(verbose_name="タグ名(name)")),
                (
                    "image_url",
                    models.CharField(max_length=200, verbose_name="画像(image_url)"),
                ),
                ("color", models.CharField(max_length=100, verbose_name="指定色(color)")),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100, verbose_name="タイトル(title)")),
                ("amount", models.IntegerField(verbose_name="金額(amount)")),
                ("date", models.DateField(verbose_name="日付(date)")),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="expenses.tag",
                    ),
                ),
            ],
        ),
    ]
