# Generated by Django 5.2 on 2025-05-12 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="user_id",
            new_name="user",
        ),
    ]
