# Generated by Django 5.2 on 2025-05-12 23:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_prefectures_remove_user_account_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budgetsetting",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="prefecture_id",
            new_name="prefecture",
        ),
    ]
