# Generated by Django 5.2.1 on 2025-05-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_user_id_budgetsetting_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetsetting',
            name='max_weekly_limit',
            field=models.IntegerField(default=0, verbose_name='週間上限金額(max_weekly_limit)'),
        ),
        migrations.AlterField(
            model_name='budgetsetting',
            name='monthly_buffer',
            field=models.IntegerField(default=0, verbose_name='月間予備金(monthly_buffer)'),
        ),
    ]
